### ISSUE TITLE
[VST] Scaler v1.8.1

### ISSUE THREAD

**Issue by sbaum** [osxmidi/LinVst#107]
Hi, I'm trying to use Scaler (commercial chord generator vst, see scalerplugin.com) with Bitwig Studio running on Kubuntu 18.04.

The Scaler plugin seems to be running fine, but Bitwig does not receive any MIDI data from the plugin. The plugin can generate audio itself (working) or it can send just the MIDI data (chords) to the DAW (not working).

Should that work? What can I possibly be doing wrong? Or does LinVst support audio generating vst plugins only?

(By the way, it's working with latest Carla v2.1alpha vst bridge. So I could switch over to using Carla. But I'd prefer LinVst if Scaler would be working with it.)

**Comment by cameronleger** [comment]
Let me know if you need any help with debugging this. I've noticed that Bitwig + LinVst + wine-staging has basically broken Scaler for me sometime this year. It's probably not LinVst specific though. It also happened on updates to those and _not_ Scaler, and recent Scaler versions have not improved. On any MIDI Output generated from the plugin, or sometimes when MIDI Input happens and the GUI is open, the plugin crashes.

**Comment by osxmidi** [comment]
If you put 2 midi synth plugins on the same track (I'm using Reaper) and set then to different presets or settings and the sound is just coming from the first plugin, then that plugin is not passing midi events to the next plugin.

There is a vst function that plugins need to implement to be able to pass midi events back to the host/next plugin, and if it's not implemented then the midi events don't get passed on.

Also there is this from a Bitwig user https://linuxmusicians.com/viewtopic.php?t=18455

**Comment by fractalf** [comment]
I'm having the exact same problem with a free vst midi plugin (Chordz). I've also tried other midi-plugins, and can't get any of them to pass the midi signal to the next device in the chain (BitWig).

@osxmidi Is your theory that the problem is that the plugins haven't implemented all VST functions properly? Why is it then working in Reaper etc

Here's my thread describing the issue:
https://linuxmusicians.com/viewtopic.php?f=62&t=20646&p=111844

I've also looked at that link you posted osxmidi, as it was suggested, but I couldn't get it working (maybe I didn't really understand what he meant).

Thanks :)

**Comment by cameronleger** [comment]
As far as I can tell, this is not an issue with VSTs that aren't handling the messages correctly, and I'm pretty familiar with those messages. This is a larger issue with Bitwig and WINE-based wrappers, I presume because it's working for multiple users with Reaper, Ardour, and Renoise, and for other native VSTs. I remember this working months ago, but probably a Bitwig update has changed that.

For me, the issue is that when one of these WINE-wrapped VSTs that alters MIDI messages, like Scaler or Chordz, is put into Bitwig, then any MIDI messages sent into them or any that are generated by them cause a severe bug where MIDI basically stops working completely and sometimes the Audio Engine will stall as well.

It's easily reproducible, but I'm happy to help debug.
