### ISSUE TITLE
T-Racks Plugins not keeping their settings

### ISSUE THREAD

**Issue by lentferj** [osxmidi/LinVst#121]
I have a few problems with TR5 plugins not keeping their settings when loading a session in Mixbus. I experienced these with Master Match and the new Tape Machine plugins. For example with master match it seems to save the calculated EQ curve, but it loses the settings for the two faders when saving, quiting and loading the session again.

![image](https://user-images.githubusercontent.com/5664183/67842262-1c97f700-fafa-11e9-919a-ea172cbb5fb3.png)

**Comment by lentferj** [comment]
I just tried to add "-DCHUNKBUF" as mentioned on another issue thread, but that didn't fix it either.
I am currently on 2dfc79b0227590c4b7df88b1c31467d5bfe8c33b.

**Comment by keybreak** [comment]
@lentferj 
Hey! :smile: 

Have you tested with other DAW?

Is it saving chosen preset but doesn't save tweaked parameters or both presets / parameters not saved?

Have you tested that your version of TR5 saves preset / parameters on Windows?
_______

I'll get to test T-Racks 5 myself in a range of next 2-4 days too, wonder how it goes since i use those plugins a lot in my workflow...

**Comment by keybreak** [comment]
Have tested **IK multimedia T-RackS complete v5.2.1** VST2 x64 plugins in **Renoise Linux x64 v3.2.0**, and all of them saves and works good for me.

Check [results](https://keybreak.github.io/linux-vst-compatibility-list/), search by *IK multimedia*, and if you want to know more about [methodology](https://github.com/keybreak/linux-vst-compatibility-list).

P.S. By High CPU in some of plugins i mean it's x2 of Windows, but still usable, except maybe Tape machines which is also x2 of Windows and hits nearly 45-50% for I7-4770K...But that's another story :smile: 
__________

@osxmidi
Looks like perhaps it's some of previous versions of T-Racks that @lentferj have been using, because since 5.0 it wasn't without the bugs, including saving as far as i recall...But 5.2.1 is fine.

Or this is Mixbus specific. which most likely is the case.

**Comment by lentferj** [comment]
Sorry for the late response. I was still running wine-4.1 (from winehq) and it took me a while to upgrade because iLok License Manager wouldn't work after the upgrade, so I needed to migrate all my iLok licensense first. Anyway, after upgrading to wine-4.19 and recompiling LinVST I can confirm that changes made to settings in TR5 Tape and TR5 Mastermatch plugins are stored and recalled on session load now. I am closing this.
