### ISSUE TITLE
LinVst not showing up in Reaper

### ISSUE THREAD

**Issue by AxxlForce** [osxmidi/LinVst#2]
Making LinVst works fine. I copied the files to /usr/bin and renamed and moved linvst.so to match my win VST and set the VST directory in the DAW but it won't show up in Reaper. Any tips for troubleshooting?

**Comment by osxmidi** [comment]
Can you load it by using Reaper's vst name loading feature instead of the scanning?

In Options->Preferences->VST there is an option to "Get VST names/types when scanning" that can be turned off (and an additional default generic UI option as well).

After the scanning is turned off and applied, then a Clear cache/re-scan needs to be done and then the actual name of the vst can be loaded.

So if linvst.so was renamed to test.so, then test.so shold show up in Reaper's add vst list and then it can be loaded.

**Comment by osxmidi** [comment]
I had some untested code changes I put up yesterday, and they had some problems which are now fixed.
