### ISSUE TITLE
CHOW Crashes in Reaper 6.47 when enabling UI

### ISSUE THREAD

**Issue by v1s1n** [osxmidi/LinVst#215]
I've checked this on both LinVst and LinVst3, for the vst and vst3 versions of the plugin respectively. Opening the UI causes reaper to hang indefinitely and eventually crash. Reaper version 6.47, current linvst version, wine-staging version 7.2, running Debian 11 on the lowlatency kernel 5.10.0-051000. 

https://github.com/Chowdhury-DSP/CHOW

**Comment by v1s1n** [comment]
This is probably a problem with reaper, wine and/or chow, as yabridge has the same problem.

**Comment by osxmidi** [comment]
> I've checked this on both LinVst and LinVst3, for the vst and vst3 versions of the plugin respectively. Opening the UI causes reaper to hang indefinitely and eventually crash. Reaper version 6.47, current linvst version, wine-staging version 7.2, running Debian 11 on the lowlatency kernel 5.10.0-051000.
> 
> https://github.com/Chowdhury-DSP/CHOW

It seems the vst has bugs.

The version on the releases page is version 1.0, but they have made changes to the code since that was released and the code version is version 1.1.

Version 1.1 seems to work ok and I'll include it below

[Win.zip](https://github.com/osxmidi/LinVst/files/8101230/Win.zip)
