### ISSUE TITLE
Some Bugs ...

### ISSUE THREAD

**Issue by re23071998** [osxmidi/LinVst#24]
Hi, i've tested Serum with LinVst-1.7.6 and here's the result:

Serum only WORKS with standalone-window-version. BUT:
- it doesnt react to MIDI events.
- it doesnt output audio.
- i cant close the plugins window (bitwig says "saving plugin states").

I have d2d1 disabled and override gdiplus (winetricks gdiplus)

I also tested another plugins and most of them WORKS with embedded-version but i cant use my keyboard for typing inside plugin window (like typing knobs/parameters value)

bitwig 2.2.2
wine-staging 2.19 (32bit wineprefix)
ubuntu 16.04.3
linux 4.10.0-38-generic

Thanks,

**Comment by re23071998** [comment]
serum crashlog https://pastebin.com/raw/NvMEVX6g

**Comment by osxmidi** [comment]
I've just tested the 64 bit and 32 bit Serum vst's with Bitwig 2.2.2 and Reaper and the embedded LinVst version, and they work ok but with some flickering with d2d1 disabled.

My system is Ubuntu Studio 16.10, wine staging 2.20, dual core laptop.

I'll look into it further.

**Comment by osxmidi** [comment]
The problem is Wine's d2d1 which is improving but not quite there yet and it can result in instability and crashes and disabling it is not an ideal solution either.

There are some people that have got the 32 bit Serum working ok with a certain dll override that is version dependent.

Check the Reaper Pre Release forum and the Last page of the Linux how to use windows plugins for someone that seems to have got it working ok.
