### ISSUE TITLE
[Ardour] No possibility to save state & further instantiation impossible 

### ISSUE THREAD

**Issue by hypsinom** [osxmidi/LinVst#32]
I cannot have my lxvst working after a relaunch of Ardour. 

I used the aur package. I also modified by putting the rights paths for wine and the libraries of it. 

But I still can't have another session unless my plugin crash. 

If you can give me a tip. It will be great.

**Comment by osxmidi** [comment]
I don't think I've heard of this problem before.

Maybe something has been corrupted or something.

Maybe deleting Ardour's (hidden) preferences in your home folder and then starting Ardour and rescan for plugins and/or reinstalling Ardour might help.

Can you add any more details about what led to the problem?

What were you trying to install etc?

**Comment by hypsinom** [comment]
No It's the same. 

First I had this 

`VST '/home/test/.wine/drive_c/Program Files/Vstplugins/TAL-BassLine.so': fixme:heap:RtlSetHeapInformation 0x590000 0 0x23e290 4 stub
VST '/home/test/.wine/drive_c/Program Files/Vstplugins/TAL-BassLine.so': RemoteVSTServer::terminate: setting exiting flag`

And for the next launch of ardour, the plug in instantiate. But after... The plugin is again not responding.

**Comment by osxmidi** [comment]
Ok, I'll try and see if I can replicate it and then I'll get back to you later on.

**Comment by osxmidi** [comment]
I tried it out with Ardour 5 and wine staging 2.16 on Debian Stretch and I can't seem to duplicate the problem.

Maybe it's some sort of problem that happens with your system, I don't know.

![ardour](https://user-images.githubusercontent.com/26504179/35717251-ea1a044e-07d5-11e8-9b53-cd2ff78b69a0.png)

**Comment by osxmidi** [comment]
I would guess from your command line output that there might be something with your wine, but it's hard to be sure.

**Comment by hypsinom** [comment]
no In fact, even If I don't modify some parameters of the plugin. It's not instantiating. 
IT's one time in two. It's really weird.

**Comment by osxmidi** [comment]
Does it happen with other windows plugins and LinVst?

It looks like LinVst is shutting down early because of an error and then Ardour can't find it anymore.

LinVst only shuts down early if a severe error has happened, and what is causing the error I don't know.

I can't seem to replicate it and I havn't heard from anyone else that has that early shutdown error and some of the LinVst users use Arch (which I think you are using).

**Comment by hypsinom** [comment]
hi, I started again, but on a fresh installation. And the one we used "tal-bassline", is now blacklisted. 
I tried to override dlls, but it's always blacklisted.. 
I cannot find a solution.

**Comment by osxmidi** [comment]
Very strange.

I have heard that some pre made versions of Ardour can apparently have library conflicts between the Ardour libraries and the libraries that are on the system.

What I would do is try the Tal Bassline plugin with Linux Reaper and see if it runs ok, then if it does it means that the problem is probably with Ardour.

**Comment by hypsinom** [comment]
the VST TAL-BassLine is finally recognized by ardour but at the first launch. It fails. I have this 

`Loading  /home/lexou/.wine/drive_c/Program Files/VstPlugins/TAL-BassLine.dll
VST '/home/lexou/.wine/drive_c/Program Files/VstPlugins/TAL-BassLine.so': fixme:heap:RtlSetHeapInformation 0x590000 0 0x23e290 4 stub
VST '/home/lexou/.wine/drive_c/Program Files/VstPlugins/TAL-BassLine.so': RemoteVSTServer::terminate: setting exiting flag
VST '/usr/lib/carla/styles/carlastyle.so': [WARNING]: Cannot get LinuxVST information from '/usr/lib/carla/styles/carlastyle.so': load failed.
VST '/usr/lib/vst/carla.vst/libcarla_interposer-safe.so': [WARNING]: Cannot get LinuxVST information from '/usr/lib/vst/carla.vst/libcarla_interposer-safe.so': load failed.
VST '/usr/lib/vst/carla.vst/libcarla_utils.so': [WARNING]: Cannot get LinuxVST information from '/usr/lib/vst/carla.vst/libcarla_utils.so': load failed.
VST '/usr/lib/vst/carla.vst/CarlaPatchbay.so': [31mCarla assertion failure: "fIsActive" in file carla-vst.cpp, line 244[0m
VST '/usr/lib/vst/carla.vst/carla-bridge-lv2.so': [WARNING]: Cannot get LinuxVST information from '/usr/lib/vst/carla.vst/carla-bridge-lv2.so': load failed.
VST '/usr/lib/vst/carla.vst/libcarla_interposer-jack-x11.so': [WARNING]: Cannot get LinuxVST information from '/usr/lib/vst/carla.vst/libcarla_interposer-jack-x11.so': load failed.
VST '/usr/lib/vst/carla.vst/CarlaRack.so': [31mCarla assertion failure: "fIsActive" in file carla-vst.cpp, line 244[0m
VST '/usr/lib/vst/carla.vst/CarlaRackFX.so': [31mCarla assertion failure: "fIsActive" in file carla-vst.cpp, line 244[0m
VST '/usr/lib/vst/carla.vst/CarlaPatchbayFX.so': [31mCarla assertion failure: "fIsActive" in file carla-vst.cpp, line 244[0m
VST '/usr/lib/vst/carla.vst/CarlaPatchbay16.so': [31mCarla assertion failure: "fIsActive" in file carla-vst.cpp, line 244[0m
VST '/usr/lib/vst/carla.vst/libcarla_interposer-x11.so': [WARNING]: Cannot get LinuxVST information from '/usr/lib/vst/carla.vst/libcarla_interposer-x11.so': load failed.
** ERROR ** VSTFX : TAL-BassLine could not be instantiated :(`

**Comment by osxmidi** [comment]
It seems like a Ardour plugin scan problem of some sort, probably due to library conflicts between Ardour and the plugins.

I've had a similar error when testing Ardour with AV Linux 32 bit.

I would point Ardour to only use a new plugin folder where the plugins are added one by one and if they don't produce an error then they are ok.

The only problem is that if you have say 200 plugins then that is tedious, so only do it for vst plugins and forget any lv2 etc plugins for the new plugin folder.

In fact I would just try a new plugin folder that only had LinVst in it and have Ardour scan LinVst plugins only and see of that works and if it does then LinVst is not part of the problem.

Also, on some slower systems Wine can need to be pre run by running winecfg first so that it loads it's libraries into cache/memory otherwise LinVst might time out trying to communicate with Wine, but that is only for slower systems ie slower hard disk etc.
