### ISSUE TITLE
Where are the binaries? (Plus general packaging / installation questions) 

### ISSUE THREAD

**Issue by eeshugerman** [osxmidi/LinVst#35]
Man, LinVst is great! I just got mine built from source and was thinking how nice 
it would be if there were pre-compiled binaries for non-programmers / Linux noobs. I saw someone mention "released binaries" in another issue here, but I don't see them in the repo.

Would this actually ease installation, or would the user still need to install all the same packages? I've been reading about this stuff, but clearly I still don't have a strong grasp of it. From what I can tell a statically linked binary would make installation a breeze but I'm not sure if that's feasible here and it seems static linking is uncommon these days. Not sure about dynamically linked - - would it mean users doesn't need the dev version of dependencies? 

A .deb would take care of dependencies right? 

Have you considered adding LinVst to the Debian or Ubuntu repos? (I understand this could be a lot of work / a pain in the neck -- this isn't a request, just curious to hear your thoughts on the matter).

Lastly, does Steinberg's licensing complicate all this?

Thanks for your incredible work!

**Comment by osxmidi** [comment]
Thanks.

I think that Arch has some sort of LinVst package and AVLinux has a LinVst package.

There are LinVst binary releases at https://github.com/osxmidi/LinVst/releases

I don't use static linking because it seems to work ok without it.

The Steinberg licencing applies to the vst sdk and LinVst uses the headers from it but they can't be included in the LinVst project but anyone can download them from Steinberg.

LinVst could also maybe use the vestige headers but they might need to be modified for it to work.

**Comment by eeshugerman** [comment]
Oh wow, I don't know how I missed that! Thanks.
