### ISSUE TITLE
How can i choose WINEPREFIX folder?

### ISSUE THREAD

**Issue by wastee** [osxmidi/LinVst#4]
I copied and renamed the so file into the kontakt.dll folder. And i add this folder into REAPER Linux. 
When i scan plug-in in REAPER, i saw i create ".wine" folder.  
But my kontakt is not installed in default ".wine" prefix. 
How can i choose the right WINEPREFIX folder? 

Using LinVst 1.0 from realease.

I love LinVst. Thank you!

**Comment by osxmidi** [comment]
Hi,

When LinVst starts up it hooks onto the WINEPREFIX environment variable, so whatever that is set to will be the wineprefix used.

In Ubuntu it would be something like this in the terminal

export WINEPREFIX=~/.wine-new

and then start the DAW from that terminal and then use LinVst in the DAW.

There are startup options in various distros for making environment variables (like WINEPREFIX ) more permanent and across the board so that the environment variables don't need to be set from a terminal.

https://wiki.winehq.org/FAQ#Can_I_store_the_virtual_Windows_installation_somewhere_other_than_.7E.2F.wine.3F

**Comment by wastee** [comment]
Thanks for your reply. If my vsts installed in more than one WINEPREFIX, how can do that in terminal? It seems can't export more than one WINEPREFIX. Thanks!

**Comment by osxmidi** [comment]
I think that different terminals can have different WINEPREFIX setings.

Another way is to change the WINEPREFIX to whatever before using a wine based program such as LinVst.

I don't think that it's possible to load multiple vsts in a DAW and then have LinVst pointing to different WINEPREFIX's at the same time for the multiple vsts.

Once the WINEPREFIX is set, then I think that's basically the one that will be used.

I'll look into multiple vsts/multiple WINEPREFIX settings some more and see if LinVst can maybe be modded somehow to handle them.
