### ISSUE TITLE
linvst doenst close after closing host

### ISSUE THREAD

**Issue by durutti** [osxmidi/LinVst#49]
Hi again, 
Linvst (both the embedded and the standalone versions) stay open when i top and the host is closed (on whatever plugin)
I am using the 2.3.1 debian stretch version on ubuntu 16.04/ mIxbus 4.3 and wine-devel 3.16
Thank you

**Comment by osxmidi** [comment]
The host is supposed to sens an EffectClose message to the vst's (including LinVst).

LinVst can't close without the  EffectClose message being sent by the host because iLinVst is a wrapper and needs to close down some system things and clean up a few things  whereas a native vst plugin might appear to close without an EffectClose being sent by the host but that is not ideal because various plugins might do some cleaning up when an EffectClose is sent by the host.

I have seen Tracktion (version 4 I think) not send an EffectClose message due to a bug in their code.

I don't know what Mixbus is doing but it seems like LinVst maybe isn't getting an EffectClose.

**Comment by lentferj** [comment]
Mixbus 4.3 will do the same as Ardour 5.x. I am also using linVST with Mixbus 4.x and have never seen any linvst processes hang after a clean shutdown of Mixbus - only on the host crashing.

**Comment by durutti** [comment]
Indeed I dont think its the host, because the same plugins dont hang wineserver with the other vst wrapper i use. However with the other wrapper I cannot overcome the wine issue with the embedded window.
So its probably something on my system that causes this issue?

**Comment by osxmidi** [comment]
> Indeed I dont think its the host, because the same plugins dont hang wineserver with the other vst wrapper i use. However with the other wrapper I cannot overcome the wine issue with the embedded window.
> So its probably something on my system that causes this issue?

Could be.

I havn't heard of any MixBus or Ardour LinVst shutdown problems.

**Comment by durutti** [comment]
Any hints on what or where to look for?

**Comment by osxmidi** [comment]
Wine would be first.

Possible overrides doing something.

Try deleting the wine prefix (default is ~/.wine) and rebuilding it by running winecfg.
