### ISSUE TITLE
Serum runs smooth in DDMF Metaplugin but not in embedded window

### ISSUE THREAD

**Issue by BillMess** [osxmidi/LinVst#62]
I've been trying to get Serum to run in Bitwig Studio on Linux for a while now. I've got it to somewhat work with LinVst by disabling "d2d1" and installing "winetricks gdiplus", but the GUI runs very slow and is unusable. I've also tried Airwave but the graphics are glitchy. I've tried installing the 32bit d2d1 6.1.7601.17514 and setting the "MaxVersionGL" registry entry to 30002, but that didn't work.

However, I recently discovered that using Serum inside of DDMF Metaplugin runs much smoother. Running Metaplugin using Airwave makes Serum even smoother at what feels like the full 60fps. Airwave also seems to make the GUI in any plugin I try run smoother than LinVst (except graphics are glitchy for some plugins). Do you have any explanation on why this would happen, and any possible fix? I would rather not have to use Metaplugin because of workflow.

I'm running the latest version of Manjaro Budgie (because graphics in debian based distros seems to not run well on my computer for some reason). I have a AMD R9 285 graphics card and an Intel i7-4790k processor with 8GB ram.

**Comment by osxmidi** [comment]
d2d1 is not complete in wine and disabling d2d1 is not ideal either, so plugins that rely on d2d1 are probably going to exhibit some strange things.

My own experience with the 64 bit version of Serum (not the 32 bit version) is that if I disable d2d1 then it's not that bad to use.

Airwave uses what is called Xembed (a window embedding system) for the display and the Wine version of Xembed is not implemented in an ideal way (hence the Airwave Wine Xembed patch).

LinVst doesn't use Xembed, it uses X11 directly.

The DDMF Metaplugin would be running using the LinVst window.

Sluggish video performance etc etc can depend on various things, opengl drivers/setup etc, and there are so many driver etc variables that it's hard to know a simple solution except to maybe look at what others with similar systems post around the net and also wine game users because running the visual part of vst's with Wine is a bit like some of the problems that Wine game players hit as well with dlls etc.

**Comment by BillMess** [comment]
I found out that using the proprietary amdgpu-pro graphics on Ubuntu 18.04 makes graphics in general run better on my computer than the open source ones (it feels about as smooth as Windows now). However, LinVst and Airwave is still behaving the same, so it still doesn't work for me. I also ran into weird glitches while using automation in Serum through Metaplugin. The fixes in the reddit post you sent me didn't help, and I can't seem to find anything else that I haven't tried.

The last thing I'll try is seeing if I can get it to work on a friend's gaming pc, and possibly swapping hardware components with him. If not, I'll just give up for now and continue using Windows.

**Comment by BillMess** [comment]
I've been messing around with other synths, and I think I found a solution that works for me. I found out I can get a lot of the sounds I want from Bitwig's built-in synthesizers and native Linux synths such as Helm. I think I actually like the workflow better since it forces me to be more creative and think things through. Browsing presets in Serum still works, and Serum works fine when the GUI window is closed. Perhaps it was even holding me back since I've been struggling to finish anything.

I'm finally switching to Linux!
