### ISSUE TITLE
[manage] manage standalone, embed and track versions at same time

### ISSUE THREAD

**Issue by KottV** [osxmidi/LinVst#81]
Hi,

I think it would be very useful to easy install and manage different builds of LinVst.
For example:

1. convert dll's with Tracktion/Waveform version into ~/.linvsttrack. Then point Waveform to this dir.
2. convert dll's with default version to ~/.linvst and point other DAWs to it.
3. same for standalone

I guess it needs separate (optional)
path_link_folder = ~/.vst_linvst/ 
in linvstmanage.ini for dll's

PS
It's possible to install different versions already. But I ran into some troubles so I have to change line in lin-vst-server.exe to
appname="lin-vst-servertrack.exe.so"
because I use WF mostly.

Is this wrong?

**Comment by osxmidi** [comment]
The idea behind the Tracktion version is that the remotevstclient.cpp file in the Tracktion folder overwrites the remotevstclient.cpp file in the main folder and also the Tracktion makefiles in the Tracktion folder overwrite the Makefile in the main folder.

Then the Makefile (in the main folder) will make a Tracktion version that has linvst.so looking for lin-vst-servertrack.exe.

So a Tracktion version linvst.so file only looks for lin-vst-servertrack.exe (and then wine automatically  loads the associated lin-vst-servertrack.exe.so).

The Tracktion version is needed because tracktion puts the vst window in the wrong place and so LinVst needs to put in a window offset for Tracktion.

**Comment by KottV** [comment]
It seems I' was not clear. I know how Tracktion version builds and works. I checked now and can say that changing in vst-server.exe is not needed.

I mean managing of separate installations of LinVst: one linvst.so for Tracktion, another one for other DAWs without much hand work. How it can be achieved in easy way?

**Comment by lentferj** [comment]
Would it be possible to identify the calling host on load time and handle the offset when the host Tracktion and that way have just one version for Tracktion and other DAWs?

**Comment by osxmidi** [comment]
The Tracktion version can be used with other DAW's.

When the Tracktion version is used with other DAW's it doesn't do the window offset and so operates as per usual.

The reason I keep the Tracktion version separate is because I'm not sure if all Tracktion users need it with their window managers (Idon't know if Tracktion does this wrong window position with all window managers) and so I have the Tracktion version as an option.

I have thought about using the Tracktion version as the main release but because I'm not sure about Tracktion and different window managers, I keep it as a separate option.

**Comment by KottV** [comment]
>>When the Tracktion version is used with other DAW's it doesn't do the window offset and so operates as per usual.

Oh, I see now.

>>The reason I keep the Tracktion version separate is because I'm not sure if all Tracktion users need it with their window managers

Tracktion frame contains some specific controls (plugin's channels control button and others) and it presents in any WM.

AFAIK the DAWs such a  Bitwig,  Carla, Ardour uses WM frame for plugins. Reaper uses its own windows.
Actually, I know only one host which affected - AudioPluginHost from JUCE SDK

![изображение](https://user-images.githubusercontent.com/4686351/56773916-b0170500-6803-11e9-8fa2-c90fd31d21ee.png)

But this case for othere issue I think )
